version: "3.7"

services:
  postgres:
    image: postgres:13.3-alpine3.14
    restart: always
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "eth"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: "postgres"
    ports:
      - 8080:8080
