version: "3.8"

services:
  postgres:
    image: postgres:13.3-alpine3.14
    restart: always
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: "postgres"
    ports:
      - 8080:8080

  eth:
    build: "eth"
    restart: unless-stopped
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: "postgres"
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
    ports:
      - 9000:9000
